TOPDIR ?= ../..
include $(TOPDIR)/.config

$(GWEATHER_SUPPORT)_SRC += services/gweather/gweather.c
$(GWEATHER_SUPPORT)_ECMD_SRC += services/gweather/gweather_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
