TOPDIR ?= ../..
include $(TOPDIR)/.config

$(APP_SAMPLE_SUPPORT)_SRC += services/gcalendar/gcalendar.c
$(APP_SAMPLE_SUPPORT)_ECMD_SRC += services/gcalendar/gcalendar-ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
