TOPDIR ?= ../..
include $(TOPDIR)/.config

$(GCALENDAR_SUPPORT)_SRC += services/gcalendar/gcalendar.c
$(GCALENDAR_SUPPORT)_ECMD_SRC += services/gcalendar/gcalendar-ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
